package finca_ganadera;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author nanis
 */
public class adm_ganado extends javax.swing.JFrame {

    /**
     * Creates new form adm_ganado
     */
    DefaultTableModel tabla_modelo; //definiendo una variable de tipo model
    String[] VInfo_ganado=new String[4];
    public static String[][]info_all = new String[250][4];
    String[] razas = {"brahman","gyr", "holstein","normando","angus","hereford"};
    String[] potreros = {"1","2", "3","4"};
    String[] vacuna = {"si","no"};
    public static String[][] potrero1, potrero2, potrero3, potrero4,potrero5,potrero6,potrero7,potrero8;
    String[] opciones = {"1","2","3","4","5","6","7"};
    Random aleatorio = new Random();
    
    public byte u=0,d=0,t=0,c=0,n=0,s=0,e=0;
    
    public adm_ganado() {
        initComponents();
        tabla_modelo=(DefaultTableModel)t_ganado.getModel(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_ganado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        verpotreros = new javax.swing.JPanel();
        ver_potreros = new javax.swing.JLabel();
        cambiarpotreros = new javax.swing.JPanel();
        cambiar_potreros = new javax.swing.JLabel();
        llenardatos = new javax.swing.JPanel();
        llenar_datos = new javax.swing.JLabel();
        llenardatos1 = new javax.swing.JPanel();
        llenar_datos1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("info_ganado"); // NOI18N

        t_ganado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Raza", "Potrero", "Vacunación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_ganado.setName("t_ganado"); // NOI18N
        t_ganado.setSelectionBackground(new java.awt.Color(148, 237, 148));
        jScrollPane1.setViewportView(t_ganado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 500, 450));

        jPanel2.setBackground(new java.awt.Color(168, 228, 107));

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("volver");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(845, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 980, 90));

        jPanel3.setBackground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 530));

        verpotreros.setBackground(new java.awt.Color(102, 102, 102));
        verpotreros.setForeground(new java.awt.Color(102, 102, 102));

        ver_potreros.setBackground(new java.awt.Color(0, 0, 0));
        ver_potreros.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ver_potreros.setForeground(new java.awt.Color(255, 255, 255));
        ver_potreros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ver_potreros.setText("ver potreros");
        ver_potreros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver_potreros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ver_potrerosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout verpotrerosLayout = new javax.swing.GroupLayout(verpotreros);
        verpotreros.setLayout(verpotrerosLayout);
        verpotrerosLayout.setHorizontalGroup(
            verpotrerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ver_potreros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        verpotrerosLayout.setVerticalGroup(
            verpotrerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ver_potreros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(verpotreros, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 170, 50));

        cambiarpotreros.setBackground(new java.awt.Color(102, 102, 102));
        cambiarpotreros.setForeground(new java.awt.Color(102, 102, 102));

        cambiar_potreros.setBackground(new java.awt.Color(0, 0, 0));
        cambiar_potreros.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cambiar_potreros.setForeground(new java.awt.Color(255, 255, 255));
        cambiar_potreros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambiar_potreros.setText("cambiar de potrero");
        cambiar_potreros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiar_potreros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiar_potrerosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cambiarpotrerosLayout = new javax.swing.GroupLayout(cambiarpotreros);
        cambiarpotreros.setLayout(cambiarpotrerosLayout);
        cambiarpotrerosLayout.setHorizontalGroup(
            cambiarpotrerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiar_potreros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        cambiarpotrerosLayout.setVerticalGroup(
            cambiarpotrerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiar_potreros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(cambiarpotreros, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 170, 50));

        llenardatos.setBackground(new java.awt.Color(102, 102, 102));
        llenardatos.setForeground(new java.awt.Color(102, 102, 102));

        llenar_datos.setBackground(new java.awt.Color(0, 0, 0));
        llenar_datos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        llenar_datos.setForeground(new java.awt.Color(255, 255, 255));
        llenar_datos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llenar_datos.setText("llenar datos");
        llenar_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llenar_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llenar_datosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout llenardatosLayout = new javax.swing.GroupLayout(llenardatos);
        llenardatos.setLayout(llenardatosLayout);
        llenardatosLayout.setHorizontalGroup(
            llenardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llenar_datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        llenardatosLayout.setVerticalGroup(
            llenardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llenar_datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(llenardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 170, 50));

        llenardatos1.setBackground(new java.awt.Color(102, 102, 102));
        llenardatos1.setForeground(new java.awt.Color(102, 102, 102));

        llenar_datos1.setBackground(new java.awt.Color(0, 0, 0));
        llenar_datos1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        llenar_datos1.setForeground(new java.awt.Color(255, 255, 255));
        llenar_datos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llenar_datos1.setText("llenar datos");
        llenar_datos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llenar_datos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llenar_datos1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout llenardatos1Layout = new javax.swing.GroupLayout(llenardatos1);
        llenardatos1.setLayout(llenardatos1Layout);
        llenardatos1Layout.setHorizontalGroup(
            llenardatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llenar_datos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        llenardatos1Layout.setVerticalGroup(
            llenardatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llenar_datos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(llenardatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        login log = new login();
            log.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ver_potrerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver_potrerosMouseClicked
        if(tabla_modelo.getRowCount()!=0){
            potreros pot = new potreros();
            pot.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "error: llene la tabla antes de continuar");
        }
    }//GEN-LAST:event_ver_potrerosMouseClicked

    private void cambiar_potrerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiar_potrerosMouseClicked
        try{
            int fila_sel=-1; //variable pa saber en q fila estoy. -1 significa ninguna fila seleccionada
            String opcion;
            fila_sel=t_ganado.getSelectedRow();//me da el número de fila seleccionada
            
            if(fila_sel==-1){
                JOptionPane.showMessageDialog(null, "error: seleccione una fila de la tabla");
            }else{
                opcion= (String) JOptionPane.showInputDialog(null, "seleccione un potrero","cambiar potreros", JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
                if(t_ganado.getValueAt(fila_sel, 2).equals(opcion)){
                    JOptionPane.showMessageDialog(null, "el animal ya se encuentra en el potrero seleccionado");
                }
                else{
                    for(int i=0;i<info_all.length;i++){
                        for(int j=0;j<4;j++){
                                if(t_ganado.getValueAt(fila_sel, 0).equals(info_all[i][0])){
                                        info_all[i][2]=opcion;
                                        t_ganado.setValueAt(opcion.toString(), fila_sel, 2);
                                        u=0;d=0;t=0;c=0;n=0;s=0;e=0;
                                        actualizar();
                                        adm_potreros();
                                }
                        }
                   }
                }
            }
            
        }catch(Exception error){
            System.out.println("Error al cambiar potreros");
        }
    }//GEN-LAST:event_cambiar_potrerosMouseClicked

    private void llenar_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenar_datosMouseClicked
        if(tabla_modelo.getRowCount() < 250){
            insert();
            actualizar();
            adm_potreros();
        }else{
            JOptionPane.showMessageDialog(null, "error: la tabla ya está llena");
        }
    }//GEN-LAST:event_llenar_datosMouseClicked

    private void llenar_datos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenar_datos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_llenar_datos1MouseClicked

    public void actualizar(){
        try{
            for(int i=0; i <info_all.length;i++){
                for(int j=0;j<4;j++){
                    switch(info_all[i][j]){
                        case "1" -> u++;
                        case "2" -> d++;
                        case "3" -> t++;
                        case "4" -> c++;
                        case "5" -> n++;
                        case "6" -> s++;
                        case "7" -> e++;
                    }
                }
            }
            potrero1= new String[u][4];
            potrero2= new String[d][4];
            potrero3= new String[t][4];
            potrero4= new String[c][4];
            potrero5= new String[n][4];
            potrero6= new String[s][4];
            potrero7= new String[e][4];
            
            
            
        }catch(Exception error){
            System.out.println("error al actualizar" + error);
        }
    }
    
    public void insert(){
        try{
            for(int i=0;i<250;i++){
                //generación de código aleatorio para todo el ganado
                VInfo_ganado[0]=String.valueOf(1000+(aleatorio.nextInt(4000-1000)+1));
                info_all[i][0]=VInfo_ganado[0];
                
                //raza aleatoria
                int e=aleatorio.nextInt(razas.length);
                VInfo_ganado[1]=razas[e];
                info_all[i][1]=VInfo_ganado[1];
                
                //potrero aleatorio
                int p=aleatorio.nextInt(potreros.length);
                VInfo_ganado[2]=potreros[p];
                info_all[i][2]=VInfo_ganado[2];
                
                //vacuna
                int v=aleatorio.nextInt(vacuna.length);
                VInfo_ganado[3]=vacuna[v];
                info_all[i][3]=VInfo_ganado[3];
                
                //añade información a la tabla
                tabla_modelo.addRow(VInfo_ganado);
            }
            
            
            
        }catch(Exception error){
            System.out.println("error insert " + error);
        }
    }
    
    
    public void adm_potreros(){
        try{
            
            for(int i=0;i<info_all.length;i++){
                for(int j=0;j<4;j++){
                    switch(info_all[i][j]){
                        case "1" -> {
                            for(int u=0;u<potrero1.length;u++){
                                if(potrero1[u][0]==null){
                                    potrero1[u][0]=info_all[i][0];potrero1[u][1]=info_all[i][1];potrero1[u][2]=info_all[i][2];potrero1[u][3]=info_all[i][3];
                                    break;
                                } 
                            }
                        }
                            
                        case "2" -> {
                            for(int u=0;u<potrero2.length;u++){
                                if(potrero2[u][0]==null){
                                    potrero2[u][0]=info_all[i][0];potrero2[u][1]=info_all[i][1];potrero2[u][2]=info_all[i][2];potrero2[u][3]=info_all[i][3];
                                    break;
                                } 
                            }
                        }
                            
                            case "3" -> {
                                for(int u=0;u<potrero3.length;u++){
                                    if(potrero3[u][0]==null){
                                        potrero3[u][0]=info_all[i][0];potrero3[u][1]=info_all[i][1];potrero3[u][2]=info_all[i][2];potrero3[u][3]=info_all[i][3];
                                        break;
                                    }
                                }
                        }
                            
                            case "4" -> {
                                for(int u=0;u<potrero4.length;u++){
                                    if(potrero4[u][0]==null){
                                        potrero4[u][0]=info_all[i][0];potrero4[u][1]=info_all[i][1];potrero4[u][2]=info_all[i][2];potrero4[u][3]=info_all[i][3];
                                        break;
                                    }
                                }
                        }
                            
                            case "5" -> {
                                for(int u=0;u<potrero5.length;u++){
                                    if(potrero5[u][0]==null){
                                        potrero5[u][0]=info_all[i][0];potrero5[u][1]=info_all[i][1];potrero5[u][2]=info_all[i][2];potrero5[u][3]=info_all[i][3];
                                        break;
                                    }
                                }
                        }
                            
                            case "6" -> {
                                for(int u=0;u<potrero6.length;u++){
                                    if(potrero6[u][0]==null){
                                        potrero6[u][0]=info_all[i][0];potrero6[u][1]=info_all[i][1];potrero6[u][2]=info_all[i][2];potrero6[u][3]=info_all[i][3];
                                        break;
                                    }
                                }
                        }
                            
                            case "7" -> {
                                for(int u=0;u<potrero7.length;u++){
                                    if(potrero7[u][0]==null){
                                        potrero7[u][0]=info_all[i][0];potrero7[u][1]=info_all[i][1];potrero7[u][2]=info_all[i][2];potrero7[u][3]=info_all[i][3];
                                        break;
                                    }
                                }
                        }

                    }
                }
            }
            
            
        }catch(Exception error){
            System.out.println("error adm " + error);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adm_ganado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cambiar_potreros;
    private javax.swing.JPanel cambiarpotreros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel llenar_datos;
    private javax.swing.JLabel llenar_datos1;
    private javax.swing.JPanel llenardatos;
    private javax.swing.JPanel llenardatos1;
    private javax.swing.JTable t_ganado;
    private javax.swing.JLabel ver_potreros;
    private javax.swing.JPanel verpotreros;
    // End of variables declaration//GEN-END:variables
}
