/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finca_ganadera;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author nanis
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imgs/milk.png"));
        this.setIconImage(icon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        experience = new javax.swing.JLabel();
        golden = new javax.swing.JLabel();
        vaquita = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        headertxt = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        usuariotxt = new javax.swing.JTextField();
        iniciar_sesion1 = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        contraseñatxt = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        boton_entrar = new javax.swing.JPanel();
        entrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setName("bg"); // NOI18N
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        experience.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        experience.setForeground(new java.awt.Color(255, 255, 255));
        experience.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        experience.setText("EXPERIENCE");
        bg.add(experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 270, 40));

        golden.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        golden.setForeground(new java.awt.Color(255, 255, 255));
        golden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        golden.setText("GOLDEN");
        bg.add(golden, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 270, 40));

        vaquita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaquita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/moooo.png"))); // NOI18N
        vaquita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(vaquita, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 270, 170));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/grass.jpg"))); // NOI18N
        bg.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 270, 510));

        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/favicon.png"))); // NOI18N
        bg.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        headertxt.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        headertxt.setText("Debe identificarse para continuar");
        bg.add(headertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        iniciar_sesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        iniciar_sesion.setText("INICIAR SESIÓN");
        bg.add(iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        usuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        usuario.setText("usuario");
        bg.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        usuariotxt.setEditable(false);
        usuariotxt.setBackground(new java.awt.Color(255, 255, 255));
        usuariotxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        usuariotxt.setForeground(new java.awt.Color(204, 204, 204));
        usuariotxt.setText("ingrese su nombre de usuario");
        usuariotxt.setBorder(null);
        usuariotxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuariotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuariotxtMousePressed(evt);
            }
        });
        usuariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariotxtActionPerformed(evt);
            }
        });
        bg.add(usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 390, 30));

        iniciar_sesion1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        iniciar_sesion1.setText("INICIAR SESIÓN");
        bg.add(iniciar_sesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        contraseña.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        contraseña.setText("contraseña");
        bg.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        contraseñatxt.setEditable(false);
        contraseñatxt.setBackground(new java.awt.Color(255, 255, 255));
        contraseñatxt.setForeground(new java.awt.Color(204, 204, 204));
        contraseñatxt.setText("*******");
        contraseñatxt.setBorder(null);
        contraseñatxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contraseñatxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñatxtMousePressed(evt);
            }
        });
        bg.add(contraseñatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 390, 30));

        jSeparator1.setForeground(new java.awt.Color(153, 204, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 390, 10));

        jSeparator2.setForeground(new java.awt.Color(153, 204, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 390, 10));

        boton_entrar.setBackground(new java.awt.Color(204, 204, 204));
        boton_entrar.setForeground(new java.awt.Color(0, 0, 0));
        boton_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        entrar.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        entrar.setForeground(new java.awt.Color(102, 102, 102));
        entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrar.setText("entrar");
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout boton_entrarLayout = new javax.swing.GroupLayout(boton_entrar);
        boton_entrar.setLayout(boton_entrarLayout);
        boton_entrarLayout.setHorizontalGroup(
            boton_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        boton_entrarLayout.setVerticalGroup(
            boton_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(boton_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariotxtActionPerformed

    private void usuariotxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariotxtMousePressed
        if(usuariotxt.getText().equals("ingrese su nombre de usuario")){
            usuariotxt.setEditable(true);
            usuariotxt.setText("");
            usuariotxt.setForeground(Color.black);
        }
        if(String.valueOf(contraseñatxt.getPassword()).isEmpty()){
            contraseñatxt.setText("*******");
            contraseñatxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usuariotxtMousePressed

    private void contraseñatxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñatxtMousePressed
        
        if(String.valueOf(contraseñatxt.getPassword()).equals("*******")){
            contraseñatxt.setEditable(true);
            contraseñatxt.setText("");
            contraseñatxt.setForeground(Color.black);
        }
        if(usuariotxt.getText().isEmpty()){
            usuariotxt.setText("ingrese su nombre de usuario");
            usuariotxt.setForeground(Color.gray);
        }

    }//GEN-LAST:event_contraseñatxtMousePressed

    private void entrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarMouseEntered

    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked
        if(usuariotxt.getText().equals("usuario") && (String.valueOf(contraseñatxt.getPassword()).equals("12345"))){
            adm_ganado gan = new adm_ganado();
            gan.setVisible(true);
            this.setVisible(false);
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Error en nombre de usuario o contraseña \nIntente de nuevo");
        }
    }//GEN-LAST:event_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel boton_entrar;
    private javax.swing.JLabel contraseña;
    private javax.swing.JPasswordField contraseñatxt;
    private javax.swing.JLabel entrar;
    private javax.swing.JLabel experience;
    private javax.swing.JLabel favicon;
    private javax.swing.JLabel golden;
    private javax.swing.JLabel headertxt;
    private javax.swing.JLabel iniciar_sesion;
    private javax.swing.JLabel iniciar_sesion1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel usuario;
    private javax.swing.JTextField usuariotxt;
    private javax.swing.JLabel vaquita;
    // End of variables declaration//GEN-END:variables
}
